[package]
name = "roitelet"
version = "0.1.0"
edition = "2021"

[dependencies]
hound = "3.5.1"
show-image = "0.13.1"
image = "0.24.7"

[profile.release]
opt-level = 3

[profile.profiling]
inherits = "release"
debug = true
strip = false